version: '{build}'
skip_tags: true

install:
  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha12-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/freetype/freetype-2.8.tar.bz2 ; exit 0"
  - tar xf freetype-2.8.tar.bz2
  - move freetype-2.8 freetype
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip ; exit 0"
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.2.4.tar.gz ; exit 0"
  - tar xf lua-5.2.4.tar.gz
  - move lua-5.2.4\src lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2017/sqlite-amalgamation-3200100.zip ; exit 0"
  - 7z x sqlite-amalgamation-3200100.zip
  - move sqlite-amalgamation-3200100 sqlite3
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://www.ambiera.at/downloads/irrKlang-32bit-1.5.0.zip ; exit 0"
  - 7z x irrKlang-32bit-1.5.0.zip
  - move irrKlang-1.5.0 irrklang

  # let premake happy
  - xcopy /E premake\* .
  
  # patch irrlicht and lua
  - patch -p0 < irrlicht\irrlicht.patch
  # - patch -p0 < lua\lua.patch
  
  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  
  - git checkout data
  - git pull origin data

  - rm -rf ygopro_222.exe
  - rm -rf irrKlang.dll
  - rm -rf ikpMP3.dll

  - mv bin\release\ygopro.exe ygopro_222.exe
  - mv irrklang\bin\win32-visualStudio\irrKlang.dll .
  - mv irrklang\bin\win32-visualStudio\ikpMP3.dll .
  
  - git add ygopro_222.exe
  - git add irrKlang.dll
  - git add ikpMP3.dll
  - git commit -m "Builded by Appveyor"
  - git push %Smile%purerosefallen/ygopro-222DIY data
  
  - 7z a -mx9 -xr!.git* ygopro-222DIY-data.7z ygopro_222.exe irrKlang.dll ikpMP3.dll lflist.conf expansions sound
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/purerosefallen/ygopro-7210srv/archive/master.zip ; exit 0"
  - 7z x ygopro-7210srv-master.zip
  - cp -rf ygopro-7210srv-master/cards.cdb .
  - cp -rf ygopro-7210srv-master/strings.conf .
  - cp -rf ygopro-7210srv-master/system.conf .
  - cp -rf ygopro-7210srv-master/textures .

  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/archive/master.zip ; exit 0"
  - 7z x ygopro-scripts-master.zip
  - mv -f ygopro-scripts-master script

  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/ygopro222-images/archive/master.zip ; exit 0"
  - 7z x ygopro222-images-master.zip
  - mv -f ygopro222-images-master pics
  
  - rm -rf pics/thumbnail pics/*.db expansions/pics/thumbnail expansions/pics/*.db
  - mkdir replay

  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-starter-pack/archive/master.zip ; exit 0"
  - 7z x ygopro-starter-pack-master.zip
  - cp -rf ygopro-starter-pack-master/* .
  
  - 7z a -mx9 -xr!.git* ygopro-222DIY-full.7z ygopro_222.exe LICENSE README.md lflist.conf strings.conf system.conf cards.cdb script textures deck single pics replay sound irrKlang.dll ikpMP3.dll expansions

test: off

artifacts:
  - path: ygopro_222.exe
    name: ygopro_222
  - path: ygopro-222DIY-data.7z
    name: ygopro-222DIY-data
  - path: ygopro-222DIY-full.7z
    name: ygopro-222DIY-full

cache:
  - premake-5.0.0-alpha12-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - freetype-2.8.tar.bz2
  - irrlicht-1.8.4.zip
  - lua-5.2.4.tar.gz
  - sqlite-amalgamation-3200100.zip
  - irrKlang-32bit-1.5.0.zip

branches:
  only:
  - local
